# Generated by Django 5.2.9 on 2026-03-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_auth_security_fixes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otprecord',
            new_name='auth_otp_re_identif_e58112_idx',
            old_name='otp_ident_chan_verified_idx',
        ),
        migrations.RenameIndex(
            model_name='otprecord',
            new_name='auth_otp_re_identif_85ff42_idx',
            old_name='otp_ident_chan_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='auth_passwo_user_id_56b27d_idx',
            old_name='pwreset_user_used_idx',
        ),
    ]
