# Generated by Django 5.2.9 on 2026-03-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_rename_otp_ident_chan_verified_idx_auth_otp_re_identif_e58112_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
