# Generated by Django 5.2.13 on 2026-05-02 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_core', '0007_phase2_employment_indexes'),
        ('hris_travel_management', '0002_alter_travelrequest_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTripBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('total_days', models.DecimalField(decimal_places=1, default=0, help_text='Set by HR through adjustments', max_digits=5, verbose_name='Total Days')),
                ('used_days', models.DecimalField(decimal_places=1, default=0, help_text='Auto updated when trip request is approved', max_digits=5, verbose_name='Used Days')),
                ('company_id', models.PositiveIntegerField(help_text='Taken from request.tenant.id — multi-tenant support', verbose_name='Company ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_trip_balances', to='hris_core.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Business Trip Balance',
                'verbose_name_plural': 'Business Trip Balances',
                'db_table': 'hris_business_trip_balances',
            },
        ),
        migrations.CreateModel(
            name='BusinessTripBalanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment_type', models.CharField(choices=[('add', 'Add'), ('deduct', 'Deduct')], max_length=10, verbose_name='Adjustment Type')),
                ('days', models.DecimalField(decimal_places=1, help_text='Delta value — always positive, direction set by adjustment_type', max_digits=5, verbose_name='Days')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason')),
                ('company_id', models.PositiveIntegerField(help_text='Taken from request.tenant.id — multi-tenant support', verbose_name='Company ID')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='hris_travel_management.businesstripbalance', verbose_name='Balance')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_trip_adjustments_made', to='hris_core.employee', verbose_name='Performed By')),
            ],
            options={
                'verbose_name': 'Business Trip Balance Adjustment',
                'verbose_name_plural': 'Business Trip Balance Adjustments',
                'db_table': 'hris_business_trip_balance_adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessTripBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100, verbose_name='Benefit Name')),
                ('code', models.SlugField(choices=[('flight_ticket', 'Flight Ticket'), ('accommodation', 'Accommodation'), ('food', 'Food'), ('other', 'Other')], default='other', verbose_name='Benefit Code')),
                ('is_fixed', models.BooleanField(default=False, help_text='True = system-defined benefit, False = manually added by HR', verbose_name='Is Fixed')),
                ('company_id', models.PositiveIntegerField(help_text='Taken from request.tenant.id  - multi-tenant support', verbose_name='Company ID')),
            ],
            options={
                'verbose_name': 'Business Trip Benefit',
                'verbose_name_plural': 'Business Trip Benefits',
                'db_table': 'hris_business_trip_benefits',
                'unique_together': {('code', 'company_id')},
            },
        ),
        migrations.CreateModel(
            name='BusinessTripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('destination', models.CharField(max_length=255, verbose_name='Destination')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Auto calculated: end_date - start_date + 1', verbose_name='Duration (days)')),
                ('details', models.TextField(blank=True, help_text='Max 1000 characters', null=True, verbose_name='Details')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of file URLs', verbose_name='Attachments')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('manager_approved', 'Manager Approved'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('interrupted', 'Interrupted')], default='pending', max_length=20, verbose_name='Status')),
                ('company_id', models.PositiveIntegerField(help_text='Taken from request.tenant.id — multi-tenant support', verbose_name='Company ID')),
                ('manager_approved_at', models.DateTimeField(blank=True, null=True)),
                ('hr_approved_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True, null=True, verbose_name='Decline Reason')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('interrupted_at', models.DateTimeField(blank=True, null=True)),
                ('interruption_date', models.DateField(blank=True, help_text='The date when the trip was manually interrupted', null=True, verbose_name='Interruption Date')),
                ('benefits', models.ManyToManyField(blank=True, related_name='trip_requests', to='hris_travel_management.businesstripbenefit', verbose_name='Benefits')),
                ('created_by', models.ForeignKey(blank=True, help_text='If manager submitted on behalf of employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_business_trip_requests', to='hris_core.employee', verbose_name='Created By')),
                ('declined_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declined_trips', to='hris_core.employee', verbose_name='Declined By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_trip_requests', to='hris_core.employee', verbose_name='Employee')),
                ('hr_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_approved_trips', to='hris_core.employee', verbose_name='HR Approved By')),
                ('interrupted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interrupted_trips', to='hris_core.employee', verbose_name='Interrupted By')),
                ('manager_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_approved_trips', to='hris_core.employee', verbose_name='Manager Approved By')),
            ],
            options={
                'verbose_name': 'Business Trip Request',
                'verbose_name_plural': 'Business Trip Requests',
                'db_table': 'hris_business_trip_requests',
            },
        ),
        migrations.CreateModel(
            name='BusinessTripActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('updated', 'Updated'), ('manager_approved', 'Manager Approved'), ('hr_approved', 'HR Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('interrupted', 'Interrupted'), ('activated', 'Activated'), ('completed', 'Completed')], max_length=20, verbose_name='Action')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('company_id', models.PositiveIntegerField(help_text='Taken from request.tenant.id — multi-tenant support', verbose_name='Company ID')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_trip_activity_logs', to='hris_core.employee', verbose_name='Performed By')),
                ('trip_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='hris_travel_management.businesstriprequest', verbose_name='Business Trip Request')),
            ],
            options={
                'verbose_name': 'Business Trip Activity Log',
                'verbose_name_plural': 'Business Trip Activity Logs',
                'db_table': 'hris_business_trip_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TravelRequest',
        ),
        migrations.AddIndex(
            model_name='businesstripbalance',
            index=models.Index(fields=['employee', 'year'], name='hris_busine_employe_87a71d_idx'),
        ),
        migrations.AddIndex(
            model_name='businesstripbalance',
            index=models.Index(fields=['company_id'], name='hris_busine_company_e2f366_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='businesstripbalance',
            unique_together={('employee', 'year')},
        ),
        migrations.AddIndex(
            model_name='businesstripbalanceadjustment',
            index=models.Index(fields=['balance'], name='hris_busine_balance_df18d6_idx'),
        ),
        migrations.AddIndex(
            model_name='businesstripbalanceadjustment',
            index=models.Index(fields=['company_id'], name='hris_busine_company_7e956e_idx'),
        ),
        migrations.AddIndex(
            model_name='businesstriprequest',
            index=models.Index(fields=['employee', 'status'], name='hris_busine_employe_5261c3_idx'),
        ),
        migrations.AddIndex(
            model_name='businesstriprequest',
            index=models.Index(fields=['employee', 'start_date', 'end_date'], name='hris_busine_employe_b9b528_idx'),
        ),
        migrations.AddIndex(
            model_name='businesstriprequest',
            index=models.Index(fields=['status'], name='hris_busine_status_2e3f38_idx'),
        ),
        migrations.AddIndex(
            model_name='businesstriprequest',
            index=models.Index(fields=['company_id'], name='hris_busine_company_b7f900_idx'),
        ),
        migrations.AddIndex(
            model_name='businesstripactivitylog',
            index=models.Index(fields=['trip_request'], name='hris_busine_trip_re_6e8bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='businesstripactivitylog',
            index=models.Index(fields=['company_id'], name='hris_busine_company_edf4c8_idx'),
        ),
    ]
