# Generated by Django 5.2.9 on 2026-04-06 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('hris_core', '0005_attendancerecord'),
        ('hris_recruitment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('vacancies', models.PositiveIntegerField(default=1, verbose_name='Number of Vacancies')),
                ('purpose', models.TextField(verbose_name='Purpose of Hiring')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20, verbose_name='Status')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_requests', to='company.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hiring_requests', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiring_requests', to='hris_core.department', verbose_name='Department')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiring_requests', to='hris_core.jobtitle', verbose_name='Job Title')),
            ],
            options={
                'verbose_name': 'Hiring Request',
                'verbose_name_plural': 'Hiring Requests',
                'db_table': 'hris_recruitment_hiring_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HiringRequestApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('role_type', models.CharField(choices=[('employee', 'Employee'), ('hr_employee', 'HR Employee'), ('direct_manager', 'Direct Manager')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('action_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hiring_request_approvals', to=settings.AUTH_USER_MODEL)),
                ('hiring_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='hris_recruitment.hiringrequest')),
            ],
            options={
                'verbose_name': 'Hiring Request Approval',
                'verbose_name_plural': 'Hiring Request Approvals',
                'db_table': 'hris_recruitment_hiring_request_approvals',
                'ordering': ['created_at'],
            },
        ),
    ]
