# Generated by Django 5.2.9 on 2026-04-06 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_recruitment', '0003_seed_recruitment_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('requirements', models.TextField(verbose_name='Requirements')),
                ('skills', models.JSONField(default=list, verbose_name='Key Skills')),
                ('responsibilities', models.TextField(verbose_name='Responsibilities')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Application Deadline')),
                ('platforms', models.JSONField(default=list, verbose_name='Published Platforms')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('hiring_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='hris_recruitment.hiringrequest')),
            ],
            options={
                'verbose_name': 'Job Advertisement',
                'verbose_name_plural': 'Job Advertisements',
                'db_table': 'hris_recruitment_job_advertisements',
                'ordering': ['-created_at'],
            },
        ),
    ]
