# Generated by Django 5.2.9 on 2026-04-06 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('hris_recruitment', '0005_seed_job_ad_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidates/photos/')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='candidates/cvs/')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Application Source')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='company.company')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'db_table': 'hris_recruitment_candidates',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('phone_screening', 'Phone Screening'), ('interview', 'Interview'), ('offer', 'Offer'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('classification', models.CharField(choices=[('shortlist_1', 'Shortlist 1'), ('shortlist_2', 'Shortlist 2'), ('none', 'None')], default='none', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hris_recruitment.candidate')),
                ('job_advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hris_recruitment.jobadvertisement')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'db_table': 'hris_recruitment_job_applications',
                'ordering': ['-applied_at'],
                'unique_together': {('candidate', 'job_advertisement')},
            },
        ),
    ]
