# Generated by Django 5.2.9 on 2026-04-06 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_core', '0005_attendancerecord'),
        ('hris_recruitment', '0007_seed_candidate_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hiringrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='hiringrequestapproval',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='jobadvertisement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hiringrequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hiringrequest',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiring_requests', to='hris_core.department'),
        ),
        migrations.AlterField(
            model_name='hiringrequest',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiring_requests', to='hris_core.jobtitle'),
        ),
        migrations.AlterField(
            model_name='hiringrequest',
            name='purpose',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hiringrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='hiringrequest',
            name='vacancies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hiringrequestapproval',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobadvertisement',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobadvertisement',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobadvertisement',
            name='platforms',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='jobadvertisement',
            name='requirements',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobadvertisement',
            name='responsibilities',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobadvertisement',
            name='skills',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='jobadvertisement',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('interview_type', models.CharField(choices=[('phone', 'Phone Screening'), ('personal', 'Personal Interview'), ('technical', 'Technical Interview')], default='phone', max_length=20)),
                ('interview_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('average_score', models.FloatField(default=0.0)),
                ('scoring_data', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='hris_recruitment.jobapplication')),
                ('interviewers', models.ManyToManyField(related_name='interviews_as_interviewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hris_recruitment_interviews',
                'ordering': ['-interview_date'],
            },
        ),
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('doc_type', models.CharField(choices=[('id_copy', 'ID Copy'), ('qualification', 'Qualification Certificate'), ('military_status', 'Military Status'), ('personal_photo', 'Personal Photo'), ('police_clearance', 'Police Clearance'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='candidates/documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hris_recruitment.candidate')),
            ],
            options={
                'db_table': 'hris_recruitment_candidate_documents',
                'unique_together': {('candidate', 'doc_type')},
            },
        ),
    ]
