# Generated by Django 5.2.9 on 2026-04-06 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_recruitment', '0009_seed_interview_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('phone', 'Phone Screening'), ('personal', 'Personal Interview')], default='phone', max_length=20),
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Base Salary')),
                ('allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Allowance')),
                ('benefits', models.TextField(blank=True, null=True, verbose_name='Benefits Package')),
                ('start_date', models.DateField(verbose_name='Proposed Start Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='hris_recruitment.jobapplication')),
            ],
            options={
                'verbose_name': 'Job Offer',
                'verbose_name_plural': 'Job Offers',
                'db_table': 'hris_recruitment_job_offers',
            },
        ),
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('tasks', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='hris_recruitment.candidate')),
            ],
            options={
                'verbose_name': 'Onboarding',
                'db_table': 'hris_recruitment_onboarding',
            },
        ),
        migrations.CreateModel(
            name='PostProbationEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('evaluation_date', models.DateField()),
                ('performance_score', models.IntegerField(default=0)),
                ('decision', models.CharField(choices=[('confirmed', 'Confirmed'), ('terminated', 'Terminated')], max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_probation', to='hris_recruitment.jobapplication')),
            ],
            options={
                'db_table': 'hris_recruitment_post_probation_evaluations',
            },
        ),
    ]
