# Generated by Django 5.2.9 on 2026-04-14 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hris_recruitment', '0017_postprobationevaluation_workflow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
        migrations.DeleteModel(
            name='JobPost',
        ),
    ]
