# Generated by Django 5.2.9 on 2026-04-11 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_core', '0005_attendancerecord'),
        ('hris_leave_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('updated', 'Updated'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('interrupted', 'Interrupted'), ('viewed', 'Viewed'), ('deleted', 'Deleted')], max_length=20, verbose_name='Action')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Leave Activity Log',
                'verbose_name_plural': 'Leave Activity Logs',
                'db_table': 'hris_leave_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(verbose_name='Year')),
                ('total_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Total Days')),
                ('used_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Used Days')),
                ('adjusted_days', models.DecimalField(decimal_places=1, default=0, help_text='+/- days adjusted by manager', max_digits=5, verbose_name='Adjusted Days')),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balances',
                'db_table': 'hris_leave_balances',
            },
        ),
        migrations.CreateModel(
            name='LeaveBalanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days', models.DecimalField(decimal_places=1, help_text='Positive = add, Negative = deduct', max_digits=5, verbose_name='Days (+/-)')),
                ('justification', models.TextField(verbose_name='Justification')),
            ],
            options={
                'verbose_name': 'Leave Balance Adjustment',
                'verbose_name_plural': 'Leave Balance Adjustments',
                'db_table': 'hris_leave_balance_adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'verbose_name': 'Leave Request', 'verbose_name_plural': 'Leave Requests'},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'verbose_name': 'Leave Type', 'verbose_name_plural': 'Leave Types'},
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='reason',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, help_text='PDF, JPG, PNG, DOCX — max 5MB', null=True, upload_to='leave_attachments/%Y/%m/', verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='If manager submitted on behalf of employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_requests', to='hris_core.employee', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='decline_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Decline Reason'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='declined_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declined_leaves', to='hris_core.employee', verbose_name='Declined By'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='details',
            field=models.TextField(blank=True, help_text='Max 1000 characters', null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='duration',
            field=models.IntegerField(default=0, help_text='Auto calculated: end_date - start_date + 1', verbose_name='Duration (days)'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hr_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hr_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_approved_leaves', to='hris_core.employee', verbose_name='HR Approved By'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='interrupted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='interrupted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interrupted_leaves', to='hris_core.employee', verbose_name='Interrupted By'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='interruption_date',
            field=models.DateField(blank=True, null=True, verbose_name='Interruption Date'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_approved_leaves', to='hris_core.employee', verbose_name='Manager Approved By'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hris_core.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hris_leave_management.leavetype', verbose_name='Leave Type'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('manager_approved', 'Manager Approved'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('interrupted', 'Interrupted')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='code',
            field=models.SlugField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('national_day', 'National Day'), ('eid_fitr', 'Eid Al-Fitr Leave'), ('eid_adha', 'Eid Al-Adha Leave'), ('hajj', 'Hajj Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('bereavement', 'Bereavement Leave'), ('work_injury', 'Work Injury Leave'), ('exceptional', 'Exceptional Leave')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='days_per_year',
            field=models.IntegerField(default=0, verbose_name='Default Days Per Year'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Leave Type Name'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'status'], name='hris_leave__employe_29ce7f_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'start_date', 'end_date'], name='hris_leave__employe_269d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status'], name='hris_leave__status_2bb049_idx'),
        ),
        migrations.AddField(
            model_name='leaveactivitylog',
            name='leave_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='hris_leave_management.leaverequest'),
        ),
        migrations.AddField(
            model_name='leaveactivitylog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_activity_logs', to='hris_core.employee'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hris_core.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hris_leave_management.leavetype', verbose_name='Leave Type'),
        ),
        migrations.AddField(
            model_name='leavebalanceadjustment',
            name='adjusted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_adjustments_made', to='hris_core.employee'),
        ),
        migrations.AddField(
            model_name='leavebalanceadjustment',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='hris_leave_management.leavebalance'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['employee', 'year'], name='hris_leave__employe_ee8df9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('employee', 'leave_type', 'year')},
        ),
    ]
