# Generated by Django 5.2.9 on 2026-04-19 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hris_leave_management', '0002_leaveactivitylog_leavebalance_leavebalanceadjustment_and_more'),
        ('hris_leave_management', '0002_phase1_employee_extensions'),
    ]

    operations = [
    ]
