# Generated by Django 5.2.13 on 2026-04-19 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_core', '0007_phase2_employment_indexes'),
        ('hris_leave_management', '0003_merge_20260419_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lm_leave_balances', to='hris_core.employee', verbose_name='Employee'),
        ),
    ]
