# Generated by Django 5.2.13 on 2026-04-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
