# Generated by Django 5.2.13 on 2026-04-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='internalloginattempt',
            new_name='internal_au_identif_170d5a_idx',
            old_name='internal_auth_ident_idx',
        ),
        migrations.RenameIndex(
            model_name='internalloginattempt',
            new_name='internal_au_user_id_411dd6_idx',
            old_name='internal_auth_user_idx',
        ),
        migrations.RenameIndex(
            model_name='internalloginattempt',
            new_name='internal_au_outcome_8f01ce_idx',
            old_name='internal_auth_outcome_idx',
        ),
    ]
