# Generated by Django 5.2.13 on 2026-04-16 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_phase1_employee_extensions'),
        ('hris_core', '0005_attendancerecord'),
        ('hris_leave_management', '0002_phase1_employee_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255, verbose_name='Allowance Name')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Allowance Value')),
            ],
            options={
                'verbose_name': 'Employee Allowance',
                'verbose_name_plural': 'Employee Allowances',
                'db_table': 'hris_employee_allowances',
            },
        ),
        migrations.CreateModel(
            name='EmployeeBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('bank_iban', models.CharField(max_length=34, verbose_name='Bank IBAN Number')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Name')),
            ],
            options={
                'verbose_name': 'Employee Bank Detail',
                'verbose_name_plural': 'Employee Bank Details',
                'db_table': 'hris_employee_bank_details',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('cost_type', models.CharField(max_length=255, verbose_name='Cost Type')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cost Value')),
                ('cost_date', models.DateField(verbose_name='Cost Date')),
            ],
            options={
                'verbose_name': 'Employee Cost',
                'verbose_name_plural': 'Employee Costs',
                'db_table': 'hris_employee_costs',
                'ordering': ['-cost_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('file', models.FileField(upload_to='employees/documents/', verbose_name='Document File')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='File Name')),
            ],
            options={
                'verbose_name': 'Employee Document',
                'verbose_name_plural': 'Employee Documents',
                'db_table': 'hris_employee_documents',
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('total_days', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Total Days')),
                ('used_days', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Used Days')),
                ('reset_date', models.DateField(blank=True, null=True, verbose_name='Balance Reset Date')),
            ],
            options={
                'verbose_name': 'Employee Leave Balance',
                'verbose_name_plural': 'Employee Leave Balances',
                'db_table': 'hris_employee_leave_balances',
            },
        ),
        migrations.AlterModelOptions(
            name='employment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='employee',
            name='fingerprint_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fingerprint ID'),
        ),
        migrations.AddField(
            model_name='employee',
            name='iqama_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending'), ('not_applicable', 'Not Applicable')], max_length=20, null=True, verbose_name='Residency Permit Status (Iqama)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_system_user',
            field=models.BooleanField(default=False, verbose_name='Active System User'),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id_job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Title on National ID'),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending')], max_length=20, null=True, verbose_name='National ID Status'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/photos/', verbose_name='Profile Photo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='hris_core.employee', verbose_name='Reporting Manager'),
        ),
        migrations.AddField(
            model_name='employee',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Secondary Phone'),
        ),
        migrations.AddField(
            model_name='employee',
            name='visa_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Visa Number'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hris_core.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='employeeassignment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='employment',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contract', 'Contract'), ('fixed_price', 'Fixed-Price Contract')], default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='employment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='employment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('probation', 'Probation'), ('on_leave', 'On Leave'), ('business_trip', 'Business Trip'), ('terminated', 'Terminated')], default='probation', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'is_deleted'], name='hris_employ_company_3456cb_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['nationality'], name='hris_employ_nationa_bbf1d3_idx'),
        ),
        migrations.AddField(
            model_name='employeeallowance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='hris_core.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='employeebankdetail',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_detail', to='hris_core.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='employeecost',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='hris_core.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hris_core.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='employeeleavebalance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hris_core.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='employeeleavebalance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_balances', to='hris_leave_management.leavetype', verbose_name='Leave Type'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeleavebalance',
            unique_together={('employee', 'leave_type')},
        ),
    ]
