# Generated by Django 5.2.13 on 2026-04-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_core', '0006_phase1_employee_extensions'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employment',
            index=models.Index(fields=['employee', 'status'], name='hris_employment_emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employment',
            index=models.Index(fields=['status'], name='hris_employment_status_idx'),
        ),
    ]
