# Generated by Django 5.2.13 on 2026-04-20 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_core', '0007_phase2_employment_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hris_core.jobtitle', verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_email',
            field=models.EmailField(blank=True, help_text='Company/system email address used for login', max_length=254, null=True, verbose_name='Work Email'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('iqama', 'Iqama / Residency Permit'), ('visa', 'Visa'), ('contract', 'Employment Contract'), ('certificate', 'Certificate'), ('other', 'Other')], default='other', max_length=20, verbose_name='Document Type'),
        ),
        migrations.CreateModel(
            name='EmployeeBusinessTripBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('total_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Balance')),
                ('used_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Used Balance')),
                ('reset_date', models.DateField(blank=True, null=True, verbose_name='Balance Reset Date')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_trip_balance', to='hris_core.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Business Trip Balance',
                'verbose_name_plural': 'Employee Business Trip Balances',
                'db_table': 'hris_employee_business_trip_balances',
            },
        ),
    ]
