[build]
builder = "dockerfile"
dockerfilePath = "docker/Dockerfile"
buildArgs = { MAXMIND_LICENSE_KEY = "${{MAXMIND_LICENSE_KEY}}" }

# cache bust: 11

[deploy]
startCommand = "celery -A config worker --loglevel=info --queues=default,fast --concurrency=2"
