# Generated by Django 5.2.13 on 2026-04-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeereview',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
